### ISSUE TITLE
README Instructions need to be updated

### ISSUE THREAD

**Issue by wjhurley** [alexandremq/RESTful-AngularJS-Spring-JPA-Hibernate#1]
The instruction that says "You can run this project locally right after downloading by using the following command where 9191 is the port listening for requests on this app:" needs to be updated. Cloning the repository and running the command `java -jar target/dependency/jetty-runner.jar...` from the root project folder returns an error `Error: Unable to access jarfile target/dependency/jetty-runner.jar`.

**Comment by alexandremq** [comment]
Hi Wjhurley, 

First of all, thank you by cloning and trying my sample project.
I hope you have already solved your problem with the jetty-runner library. It looks like to me you had a security problem in your file system, is that correct ?
I look forward to hear from you!
Best regards,
Alexandre
